DELETE http://localhost:3003/api/blogs/668cb6849b567aefc129298b HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikp1bm8gV29uZyIsImlkIjoiNjY4YzI0ZmY2MTY5N2RlNjMwYTJhMmY1IiwiaWF0IjoxNzIwNDk2ODg1LCJleHAiOjE3MjA1MDA0ODV9.k9boGJVSvPQi6FqIsHKwbCQzya0B6fmgE_TFvKw9_SU