POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikp1bm8gV29uZyIsImlkIjoiNjY4YzI0ZmY2MTY5N2RlNjMwYTJhMmY1IiwiaWF0IjoxNzIwNDcwNjExLCJleHAiOjE3MjA0NzQyMTF9.w4m_Rg2h4IeOjFyyBuZqoRUuhb8SjVzsEiqvy7VK

{
    "title": "TESTING09 - with no token",
    "author": "Vampire Weekend",
    "url": "www.blognine.com", 
    "likes" : 80
}